---

# Runs all dependencies

- name: Reboot for latest kernel headers + kernel devel
  become: true
  ansible.builtin.reboot:

- name: Re-gather facts
  ansible.builtin.setup:

- name: Install missing VirtualBox Guest Additions dependencies
  become: true
  loop: "{{ vbox_guest_dependencies[ansible_os_family] }}"
  when: item not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

...
