---

# tasks to install vbox_guest

- name: Gather package facts
  ansible.builtin.package_facts:

# TODO test VBoxClient command
- name: Check if VirtualBox kernel modules are loaded
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      lsmod | grep -E '^vboxguest|^vboxsf|^vboxvideo'
    executable: /bin/bash
  register: vbox_modules
  changed_when: false
  failed_when: vbox_modules.rc not in [0, 1]

- name: Check vbox guest version
  ansible.builtin.command:
    cmd: "VBoxControl --version"
  register: vbox_version_found
  changed_when: false
  failed_when: vbox_version_found.rc not in [0, 2]

- name: Install guest utils on Ubuntu
  when: ansible_distribution == "Ubuntu" and vbox_version_found.rc == 2
  block:
    - name: Update package cache
      become: true
      ansible.builtin.package:
        update_cache: true

    - name: Install guest utils
      become: true
      ansible.builtin.apt:
        name: virtualbox-guest-utils
        state: present

    - name: Check vbox guest version
      ansible.builtin.command:
        cmd: "VBoxControl --version"
      register: vbox_version_present
      changed_when: false
      failed_when: vbox_version_present.rc != 0

- name: Set fact for installed VirtualBox Guest Additions version
  when: vbox_version_found.rc == 0
  ansible.builtin.set_fact:
    vbox_version_present: "{{ vbox_version_found.stdout | regex_search('^[^_r]+') }}"

- name: Set fact if VirtualBox Guest Additions are already installed
  when: vbox_version_present != vbox_version_target
  ansible.builtin.set_fact:
    vbox_version_present: false

- name: Skip VirtualBox Guest Additions installation if already installed
  when: vbox_version_present
  ansible.builtin.debug:
    msg: "VirtualBox Guest Additions Version {{ vbox_version_present }} are already installed."

- name: Validate VirtualBox Guest Additions installation
  when: not vbox_version_present
  block:
    - name: Remove virtualbox-guest-utils
      become: true
      ansible.builtin.package:
        name: virtualbox-guest-utils
        state: absent

    - name: Update packages
      become: true
      ansible.builtin.package:
        name: "*"
        state: latest
        update_cache: true

    - name: Include dependencies
      ansible.builtin.include_tasks:
        file: dependencies.yml

    - name: Check if the file exists
      ansible.builtin.stat:
        path: "{{ vbox_additions_iso_path }}"
      register: iso_file_stat

    - name: Download guest additions
      when: not iso_file_stat.stat.exists
      ansible.builtin.get_url:
        url: "{{ vbox_guest_download_url }}"
        dest: "{{ ansible_env.HOME }}"
        mode: "0644"

    - name: Mount VBoxGuestAdditions.iso
      become: true
      ansible.posix.mount:
        path: /mnt
        src: "{{ vbox_additions_iso_path }}"
        fstype: iso9660
        opts: loop
        state: mounted
        fstab: /tmp/tmp.fstab

    # INFO return code 2 happens on ubuntu even tho installation is successfull
    - name: Install VirtualBox Guest Additions
      become: true
      ansible.builtin.command:
        cmd: "/mnt/VBoxLinuxAdditions.run --nox11"
      register: guest_add_install
      changed_when: guest_add_install.rc in [0, 2]
      failed_when: guest_add_install.rc not in [0, 2]

    - name: Reload VirtualBox kernel modules
      become: true
      when: guest_add_install.rc == 2
      ansible.builtin.command:
        cmd: rcvboxadd reload
      register: reload_result
      changed_when: reload_result.rc == 0
      failed_when: reload_result.rc != 0

    - name: System reboot
      become: true
      when: guest_add_install.rc == 2
      ansible.builtin.reboot:
        msg: "Rebooting after failing to reload VirtualBox kernel modules"

    - name: Check if VirtualBox Guest Additions modules are loaded
      ansible.builtin.shell: |
        lsmod | grep -E 'vboxguest|vboxsf|vboxvideo'
      register: vbox_modules_loaded
      failed_when: false
      changed_when: false

    - name: Load VirtualBox Guest Additions kernel modules if missing
      become: true
      when: vbox_modules_loaded.stdout == ''
      ansible.builtin.command:
        cmd: modprobe vboxguest && modprobe vboxsf && modprobe vboxvideo

    - name: Cleanup after installation
      ansible.builtin.include_tasks:
        file: present_cleanup.yml

...
