---
dependency:
  name: galaxy
driver:
  name: vagrant
  parallel: true
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: Alma9
    box: almalinux/9
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.20"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
    groups:
      - client
provisioner:
  name: ansible
  env:
    # ANSIBLE_VERBOSITY: 3
    ANSIBLE_DIFF_ALWAYS: false
  playbooks:
    create: ../default/create.yml
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    side_effect: ../default/side_effect.yml
    verify: ../default/verify.yml
    cleanup: ../default/cleanup.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      diff: True
      gathering: smart
      fact_caching_timeout: 3600
      fact_caching: jsonfile
      fact_caching_connection: /tmp/ansible_fact_cache
      stdout_callback: debug
      callbacks_enabled: ansible.posix.profile_tasks
    connection:
      # WARNING disable "requiretty" in hosts sudoers file on case of errors
      pipelining: true
    env:
      ANSIBLE_FORCE_COLOR: "true"
verifier:
  name: ansible
scenario:
  test_sequence:
      - dependency
      - syntax
      - create
      - prepare
      - converge
      - idempotence
      - side_effect
      - verify
      - cleanup
      - destroy
